from smart_trip.engine.models.question import Question
from smart_trip.repositories.memory.question_repo import InMemoryQuestionRepository

SEED_QUESTIONS = [
    Question(id="geo-001", category="Geography", difficulty="easy", text="What is the capital of France?", choices=["London", "Paris", "Berlin", "Madrid"], answer=1, explanation="Paris has been the capital of France since the 10th century.", source="World Geography Facts"),
    Question(id="geo-002", category="Geography", difficulty="easy", text="Which is the largest continent?", choices=["Africa", "Europe", "Asia", "North America"], answer=2, explanation="Asia is the largest continent by both area and population.", source="World Geography Facts"),
    Question(id="geo-003", category="Geography", difficulty="easy", text="What is the longest river in the world?", choices=["Amazon", "Nile", "Mississippi", "Yangtze"], answer=1, explanation="The Nile River stretches approximately 6,650 km through northeastern Africa.", source="World Geography Facts"),
    Question(id="geo-004", category="Geography", difficulty="easy", text="Which country has the most population?", choices=["India", "USA", "China", "Indonesia"], answer=0, explanation="India surpassed China as the most populous country in 2023.", source="World Population Data"),
    Question(id="geo-005", category="Geography", difficulty="easy", text="What ocean is on the west coast of the United States?", choices=["Atlantic", "Indian", "Arctic", "Pacific"], answer=3, explanation="The Pacific Ocean borders the western coast of the United States.", source="World Geography Facts"),
    Question(id="geo-006", category="Geography", difficulty="medium", text="Mount Kilimanjaro is located in which country?", choices=["Kenya", "Tanzania", "Uganda", "South Africa"], answer=1, explanation="Mount Kilimanjaro is located in Tanzania, near the border with Kenya.", source="World Geography Facts"),
    Question(id="geo-007", category="Geography", difficulty="medium", text="What is the smallest country in the world?", choices=["Monaco", "San Marino", "Vatican City", "Liechtenstein"], answer=2, explanation="Vatican City is the smallest country at just 0.44 square kilometers.", source="World Geography Facts"),
    Question(id="geo-008", category="Geography", difficulty="medium", text="Which desert is the largest hot desert in the world?", choices=["Gobi", "Kalahari", "Sahara", "Arabian"], answer=2, explanation="The Sahara Desert covers most of North Africa and is the largest hot desert.", source="World Geography Facts"),
    Question(id="geo-009", category="Geography", difficulty="medium", text="The Amazon River flows through which country primarily?", choices=["Colombia", "Peru", "Brazil", "Venezuela"], answer=2, explanation="The Amazon River flows primarily through Brazil, though its source is in Peru.", source="World Geography Facts"),
    Question(id="geo-010", category="Geography", difficulty="medium", text="Which European country has the most coastline?", choices=["Italy", "Greece", "Norway", "Spain"], answer=2, explanation="Norway has an extensive coastline with thousands of fjords and islands.", source="World Geography Facts"),
    Question(id="geo-011", category="Geography", difficulty="hard", text="What is the capital of Mongolia?", choices=["Ulaanbaatar", "Bishkek", "Astana", "Tashkent"], answer=0, explanation="Ulaanbaatar is the capital and largest city of Mongolia.", source="World Geography Facts"),
    Question(id="geo-012", category="Geography", difficulty="hard", text="Which strait separates Europe from Africa?", choices=["Strait of Hormuz", "Strait of Gibraltar", "Bosporus Strait", "Strait of Malacca"], answer=1, explanation="The Strait of Gibraltar connects the Atlantic Ocean to the Mediterranean Sea and separates Europe from Africa.", source="World Geography Facts"),
    Question(id="geo-013", category="Geography", difficulty="hard", text="What is the deepest point in the world's oceans?", choices=["Mariana Trench", "Tonga Trench", "Puerto Rico Trench", "Java Trench"], answer=0, explanation="The Mariana Trench's Challenger Deep is the deepest point at about 11,000 meters.", source="Oceanography Facts"),
    Question(id="geo-014", category="Geography", difficulty="hard", text="Which country has the most time zones?", choices=["Russia", "USA", "France", "China"], answer=2, explanation="France has the most time zones (13) due to its overseas territories.", source="World Geography Facts"),
    Question(id="geo-015", category="Geography", difficulty="hard", text="Lake Baikal is located in which country?", choices=["Mongolia", "Russia", "Kazakhstan", "China"], answer=1, explanation="Lake Baikal in Siberia, Russia, is the deepest and oldest freshwater lake.", source="World Geography Facts"),
    Question(id="geo-016", category="Geography", difficulty="easy", text="Which planet is known as the Red Planet?", choices=["Venus", "Mars", "Jupiter", "Saturn"], answer=1, explanation="Mars appears red due to iron oxide (rust) on its surface.", source="Space Facts"),
    Question(id="geo-017", category="Geography", difficulty="easy", text="What is the largest ocean?", choices=["Atlantic", "Indian", "Arctic", "Pacific"], answer=3, explanation="The Pacific Ocean covers about 63 million square miles.", source="World Geography Facts"),
    Question(id="geo-018", category="Geography", difficulty="easy", text="Which country is known as the Land of the Rising Sun?", choices=["China", "South Korea", "Japan", "Thailand"], answer=2, explanation="Japan is called the Land of the Rising Sun because it lies east of China, where the sun rises.", source="World Culture Facts"),
    Question(id="geo-019", category="Geography", difficulty="medium", text="What is the capital of Australia?", choices=["Sydney", "Melbourne", "Canberra", "Brisbane"], answer=2, explanation="Canberra was chosen as the capital as a compromise between Sydney and Melbourne.", source="World Geography Facts"),
    Question(id="geo-020", category="Geography", difficulty="medium", text="Which river flows through Baghdad?", choices=["Tigris", "Euphrates", "Nile", "Jordan"], answer=0, explanation="The Tigris River flows through Baghdad, the capital of Iraq.", source="World Geography Facts"),
]


def load_seed_data(question_repo: InMemoryQuestionRepository) -> None:
    question_repo._questions = list(SEED_QUESTIONS)
